version: '3.8'

services:
  #Laravel Service
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: ./.config/docker/Dockerfile
    container_name: my-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: my-webserver
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - 8080:80
      - 8081:81
    volumes:
      - ./:/var/www
      - ./.config/docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #Database Service
  db:
    image: mysql:5.7
    container_name: my-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'laravel-boilerplate'
      MYSQL_USER: 'laraveler'
      MYSQL_PASSWORD: 'secret'
    volumes:
      - ./storage/app/mysql_data:/var/lib/mysql
      - ./storage/logs/mysql:/var/log/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
